[package]
name = "trusttrove-test-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
trusttrove-registry = { workspace = true }
trusttrove-invoice = { workspace = true }
trusttrove-escrow = { workspace = true }
trusttrove-pool = { workspace = true }
trusttrove-ttl = { path = "../ttl" }
k256 = { version = "=0.13.4", default-features = false, features = ["ecdsa", "std"] }
